"""
====================================================================
Project : AEGIS
System  : Autonomous Enterprise Global Intelligence System
Company : Honeydewnuts Nigerian Limited

File    : credential_vault.py

Purpose :
Pydantic schemas used by the Broker Credential Vault subsystem.

Current Stage:
CP-006 Batch 2

Overview
--------
These models define the API contracts for securely creating,
retrieving and managing broker credentials.

IMPORTANT
---------
These schemas DO NOT perform encryption.

Encryption is the responsibility of:

    CredentialVaultService

The service receives the request, encrypts sensitive values using
AES-256-GCM and stores only encrypted data.

The schemas simply validate the data exchanged between the API,
services and future database layer.
====================================================================
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field


class CredentialCreateRequest(BaseModel):
    """
    Request model used when registering a new broker account.

    Notes
    -----
    • encrypted_password contains the encrypted trading password
      generated by CredentialVaultService.

    • investor_password is optional because many brokers support
      view-only access.

    • metadata allows future broker-specific configuration without
      changing this schema.
    """

    account_id: str = Field(
        ...,
        description="Unique account identifier within AEGIS.",
        examples=["ACC-000001"],
    )

    broker_name: str = Field(
        ...,
        description="Broker or trading platform name.",
        examples=["MetaTrader5"],
    )

    server: str = Field(
        ...,
        description="Broker server name.",
        examples=["ICMarketsSC-Demo"],
    )

    login: str = Field(
        ...,
        description="Broker login or account number.",
        examples=["12345678"],
    )

    encrypted_password: str = Field(
        ...,
        description="AES-256-GCM encrypted trading password.",
        examples=[
            "gAAAAABoExampleEncryptedPasswordValue"
        ],
    )

    investor_password: str | None = Field(
        default=None,
        description="Optional read-only investor password.",
        examples=["investor123"],
    )

    execution_enabled: bool = Field(
        default=True,
        description=(
            "Determines whether AEGIS is permitted to execute "
            "trades for this account."
        ),
        examples=[True],
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description=(
            "Additional broker-specific configuration values."
        ),
        examples=[
            {
                "account_type": "Demo",
                "region": "EU",
                "leverage": "1:100",
            }
        ],
    )


class CredentialResponse(BaseModel):
    """
    Returned after successful credential registration or lookup.

    Sensitive values such as trading passwords are NEVER included.
    """

    credential_id: str = Field(
        ...,
        description="Unique vault credential identifier.",
        examples=["CRED-000001"],
    )

    account_id: str = Field(
        ...,
        description="Associated AEGIS account.",
        examples=["ACC-000001"],
    )

    broker_name: str = Field(
        ...,
        description="Broker name.",
        examples=["MetaTrader5"],
    )

    server: str = Field(
        ...,
        description="Broker server.",
        examples=["ICMarketsSC-Demo"],
    )

    execution_enabled: bool = Field(
        ...,
        description="Whether automated execution is enabled.",
        examples=[True],
    )

    created_at: datetime = Field(
        ...,
        description="Credential creation timestamp.",
    )

    updated_at: datetime = Field(
        ...,
        description="Last modification timestamp.",
    )


class CredentialRotationRequest(BaseModel):
    """
    Request model used when rotating (changing)
    a broker trading password.

    Rotation is recommended periodically as part
    of enterprise security policy.
    """

    credential_id: str = Field(
        ...,
        description="Credential identifier to rotate.",
        examples=["CRED-000001"],
    )

    new_password: str = Field(
        ...,
        min_length=1,
        description="New broker trading password.",
        examples=["NewSecurePassword123!"],
    )


class BrokerConnectionInfo(BaseModel):
    """
    Lightweight model describing a broker connection.

    This object is intended to be passed to future broker
    adapters (MT5, MT4, cTrader, FIX, Binance, etc.)
    without exposing sensitive credentials.
    """

    broker_name: str = Field(
        ...,
        description="Broker platform.",
        examples=["MetaTrader5"],
    )

    server: str = Field(
        ...,
        description="Broker server.",
        examples=["ICMarketsSC-Demo"],
    )

    login: str = Field(
        ...,
        description="Broker login identifier.",
        examples=["12345678"],
    )

    execution_enabled: bool = Field(
        ...,
        description=(
            "True if automated execution is authorised."
        ),
        examples=[True],
    )
